version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: pwd
      - run: cd ./bulletin-board-app
      - run: docker login --username mangeshkdocker --password Nescafe_90
      - run: docker build -t mangeshdocker/sample-bulletin:latest . 
      - run: docker push mangeshdocker/sample-bulletin:latest

      