version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: pwd
      - run: cd /home/circleci/project/bulletin-board-app
      - run: pwd
      - run: ls
      - run: docker login --username mangeshkdocker --password Nescafe_90
      - run: docker build -t mangeshkdocker/sample-bulletin:latest /home/circleci/project/bulletin-board-app
      - run: docker push mangeshkdocker/sample-bulletin:latest

      